'use strict';
Object.assign(window.WorkshopEnglish,{
  'تعديل المتابعة':'Edit follow-up',
  'تعديل العمل':'Edit work',
  'المتابعات العامة':'General follow-ups',
  'الأحدث تعديلاً أولاً':'Most recently updated first',
  'البنود المنجزة والكتب المغلقة؛ إغلاق الكتاب مستقل عن إنجاز العمل المرتبط به.':'Completed items and closed letters. Closing a letter does not complete its linked work.',
  'نوع السجل المغلق':'Closed record type',
  'تصنيف المتابعات العامة المغلقة':'Closed general follow-up category',
  'تصفية تفصيلية للمغلقات':'Detailed closed-record filters',
  'ابحث بالموضوع أو رقم الطلب أو الكتاب أو المسؤول':'Search by subject, request or letter number, or owner',
  'البحث في المتابعات المغلقة':'Search closed follow-ups',
  'لا توجد سجلات مغلقة مطابقة':'No matching closed records',
  'غيّر النوع أو التصنيف، أو امسح البحث والتصفية.':'Change the type or category, or clear the search and filters.',
  'متابعة مرتبطة بطلب شراء — مكتملة':'Completed follow-up linked to a purchase request',
  'فتح طلب الشراء المرتبط':'Open linked purchase request',
  'إنهاء خدمة الموظف — داود علي كهوتو محمد (33707)':'Employee end of service — Dawood Ali Khuhuto Mohammed (33707)',
  'مكتب المدير العام / إدارة الموارد البشرية':"Director General's Office / Human Resources Department",
  'الكتاب مغلق وفق تحديث عبدالله بتاريخ 17/09/2026؛ المستندات محفوظة في الأرشيف.':'The letter is closed according to Abdullah’s update of 17/09/2026; the documents are archived.',
  'تم تسجيل الكتاب مغلقًا بناءً على تحديث عبدالله بتاريخ 17/09/2026. الكتاب بتاريخ 15/09/2026 وقرار إنهاء الخدمة رقم 593 لسنة 2026 بتاريخ 14/09/2026. الإغلاق المسجل يخص الكتاب؛ لم يُقدَّم تأكيد باستكمال إخلاء الطرف أو التسوية النهائية. المستندات المؤرشفة: كتاب إنهاء الخدمة ونموذج إخلاء الطرف، مراسلات استمرار الانقطاع، استمارة تجميد الراتب، القرار الإداري، وسجل حركة تراسل.':'The letter was recorded as closed based on Abdullah’s update of 17/09/2026. The letter is dated 15/09/2026, and end-of-service decision No. 593 of 2026 is dated 14/09/2026. The recorded closure applies to the letter; completion of clearance or final settlement has not been confirmed. Archived documents: the end-of-service letter and clearance form, correspondence concerning continued absence, the salary-freeze form, the administrative decision, and the Tarasel routing history.',
  'مسار الأرشفة:':'Archive path:',
  'الأعمال الفنية':'Technical work',
  'تصنيف التنسيق والجاهزية':'Coordination and readiness categories',
  'الكل':'All',
  'استعدادات الأمطار':'Rain readiness',
  'احتياجات القطاعات':'Sector requirements',
  'تسليم واسترجاع المعدات':'Equipment handover and return',
  'الدعم والتنسيق الميداني':'Field support and coordination',
  'شؤون الموظفين':'Personnel affairs',
  'الشؤون الإدارية':'Administrative affairs',
  'خطط التطوير':'Development plans',
  'مراسلات تراسل':'Tarasel correspondence',
  'لا توجد خطط تطوير مسجلة بعد':'No development plans have been recorded yet',
  'تطوير نظام المتابعة، تنظيم الأرشفة، وتحسين إجراءات العمل.':'Developing the follow-up system, organizing the archive, and improving work procedures.',
  'عرض خطط التطوير':'View development plans',
  'الطرف غير محدد':'Recipient not specified',
  'الأعمال المعلّقة':'Pending works',
  'المتابعات العامة المفتوحة':'Open general follow-ups',
  'ماذا أتابع؟':'What needs follow-up?',
  'تحتاج متابعتي':'Needs my follow-up',
  'بانتظار جهة أخرى':'Awaiting another party',
  'متأخرة':'Overdue',
  'تجاوزت موعداً مسجلاً':'Past a recorded due date',
  'عرض المتابعات':'View follow-ups',
  'عرض الكل':'View all',
  'تصفية':'Filter',
  'مسح التصفية':'Clear filters',
  'كل المتابعات العامة':'All general follow-ups',
  'من عنده الإجراء':'Action with',
  'بحاجة للانتباه':'Needs attention',
  'طرف العمل':'Work recipient',
  'مصدر الطلب':'Request source',
  'كل المصادر':'All sources',
  'تراسل':'Tarasel',
  'بريد إلكتروني':'Email',
  'تكليف داخلي':'Internal assignment',
  'غير محدد':'Not specified',
  'الأعمال المفتوحة':'Open jobs',
  'الأعمال القائمة':'Active work',
  'كل الأعمال':'All jobs',
  'المكتملة':'Completed',
  'مصدر الطلب والمراسلات':'Request source and correspondence',
  'تفاصيل المتابعة':'Follow-up details',
  'فتح التنفيذ المرتبط':'Open linked follow-up',
  'آخر حالة للتنفيذ':'Current execution status',
  'حالة العمل المسجلة في الكتاب':'Work status recorded in the letter',
  'حالة الرد':'Reply status',
  'حالة الكتاب':'Letter status',
  'الجهة صاحبة ماكينة تقطيع الأخشاب':'Department responsible for the wood chipper',
  'طلب فحص وإصلاح المضخة الهيدروليكية لماكينة تقطيع الأخشاب':'Request to inspect and repair the wood chipper hydraulic pump',
  'مراجعة حالة الكتاب والرد المسجل في تراسل.':'Review the letter status and the response recorded in Tarasel.',
  'نوع المتابعة':'Follow-up type',
  'عدد الكتب مستقل عن عدد المهام؛ افتح التنفيذ المرتبط لمتابعة الإجراء.':'Letters are counted separately from tasks. Open the linked follow-up to track execution.',
  'العمل ومراسلاته في بطاقة واحدة؛ حالة الرد وإغلاق الكتاب تظهران داخل المراسلات المرتبطة.':'Work and its correspondence in one card. Reply and closure status appear within the linked letters.',
  'كتاب مفتوح':'open letters',
  'كتب مسجلة':'registered letters',
  'الجهة غير مسجلة':'Department not recorded',
  'حالة غير مسجلة':'Status not recorded',
  'الإجراء الحالي':'Current action',
  'المراسلات المرتبطة':'Linked correspondence',
  'بانتظار جهة':'Awaiting another party',
  'متابعات مفتوحة':'Open follow-ups',
  'يشمل المهام المفتوحة فقط':'Open tasks only',
  'الأولوية ثم موعد المتابعة':'Priority, then follow-up date',
  'المهام المفتوحة دون تكرار؛ المراسلات مرتبطة بالمهام وتُعد بشكل مستقل.':'Open tasks counted once; correspondence is linked to tasks and counted separately.'
});
