/* Diesel Workshop display layer 1.1.0. Read-only; uses the existing authorized 1.0.1 API. */
(function (root) {
'use strict';
const D = {
 dashboard:['لوحة الإنجاز','Achievement dashboard'], caption:['شعبة ورشة الديزل · متابعة، إنجاز، وقياس عبء العمل','Diesel Workshop · Follow-up, achievement & workload'],
 headline:['صورة واضحة للأعمال والإنجاز','A clear view of work and achievement'], intro:['إحصائيات من سجلات الورشة. الأعداد الحالية منفصلة عن إنجاز الشهر، والبيانات غير المكتملة ظاهرة بوضوح.','Statistics from the workshop register. Current totals are separate from monthly achievement; missing information stays visible.'],
 snapshot:['لقطة السجل الحالية','Current register snapshot'], records:['سجلات','records'], task:['متابعات','Follow-ups'],job:['أعمال تفصيلية','Detailed work records'],letter:['مراسلات','Correspondence'],
 total:['إجمالي السجلات','Total records'], open:['مفتوحة الآن','Currently open'], closed:['مقفلة في المصدر','Closed at source'], cancelled:['ملغاة','Cancelled'], overdue:['متأخرة عن موعد مسجّل','Past a recorded deadline'],
 currentNote:['يشمل المتابعات والأعمال والكتب؛ ليس عدداً لعمليات الصيانة. المتأخر جزء من المفتوح.','Includes follow-ups, work records and letters; not a maintenance count. Overdue is a subset of open.'],
 monthly:['مؤشرات الشهر المختار','Selected-month indicators'], receiptNote:['الاستلام حسب تاريخ الاستلام؛ الإنجاز المعتمد حسب تاريخ الاعتماد؛ الساعات حسب يوم العمل.','Receipts use receipt date; accepted achievement uses acceptance date; hours use the work date.'],
 tasksReceived:['متابعات مستلمة','Follow-ups received'],jobsReceived:['أعمال مستلمة','Work records received'],lettersIn:['كتب واردة','Incoming letters'],lettersOut:['كتب صادرة','Outgoing letters'],completed:['أعمال اكتمل تنفيذها','Execution completed'],accepted:['أعمال معتمدة','Accepted work'],maintenance:['صيانات معتمدة','Accepted maintenance'],hours:['ساعات أفراد مسجّلة','Recorded person-hours'],overtime:['منها ساعات إضافية','Including overtime'],
 states:['حالة السجلات','Record status'],domains:['توزيع المجالات','Domain distribution'],unknown:['غير مصنّف','Unclassified'],
 maintenanceDomain:['الصيانة والفحص','Maintenance & inspection'],operations:['التشغيل والدعم','Operations & support'],procurement:['المشتريات والموازنة','Procurement & budget'],administration:['شؤون إدارية','Administration'],people:['شؤون الموظفين','Employee affairs'],development:['التطوير والتدريب','Development & training'],inventory:['المخزون والأصول','Inventory & assets'],vehicles:['المركبات والسائقون','Vehicles & drivers'],rain:['جاهزية الأمطار','Rain readiness'],
 trend:['الحركة خلال ستة أشهر','Six-month activity'],trendNote:['السجلات بلا تاريخ لا تدخل المنحنى. الصفر يعني لا توجد سجلات مؤرخة مطابقة، وليس إثباتاً لعدم وجود أعمال.','Undated records are excluded. Zero means no matching dated records, not proof that no work occurred.'],
 trendEmpty:['لا توجد تواريخ كافية لرسم الحركة خلال هذه الفترة.','There are no matching dated records to chart in this period.'],
 activity:['نوع الأعمال المعتمدة','Accepted work by activity'],activityNote:['العمل يُحسب مرة واحدة؛ تعدد المشاركين لا يضاعف عدد الأعمال. الصيانة تشمل الوقائية والتصحيحية فقط.','Each work record counts once regardless of contributors. Maintenance includes preventive and corrective work only.'],
 pm:['صيانة وقائية','Preventive maintenance'],cm:['صيانة تصحيحية','Corrective maintenance'],inspection:['فحص','Inspection'],report:['تقرير','Report'],assessment:['تقييم فني','Technical assessment'],coordination:['تنسيق ومتابعة','Coordination'],administrative:['عمل إداري','Administrative work'],training:['تدريب','Training'],rework:['إعادة عمل','Rework'],fuel:['توزيع ديزل','Diesel distribution'],transport:['نقل معدات','Equipment transport'],
 durations:['مدد المتابعة الموثّقة','Documented follow-up durations'],medianCycle:['وسيط مدة الإقفال','Median closure time'],firstAction:['وسيط أول إجراء','Median first action'],waiting:['وسيط الانتظار الموثّق','Median documented waiting'],days:['يوم تقويمي','calendar days'],sample:['حجم العينة','Sample size'],
 durationNote:['الإقفال والانتظار لمتابعات أُقفلت في الشهر المختار. أول إجراء لمتابعات استُلمت في الشهر. الانتظار لا يشمل سجلاً بلا فترة موثّقة.','Closure and waiting use follow-ups closed in the selected month. First action uses follow-ups received in that month. Waiting excludes records with no documented interval.'],
 quality:['اكتمال بيانات القياس','Measurement data coverage'],coverage:['مصنّفة بمجال','With a recorded domain'],dated:['بتاريخ استلام / إرسال','With a received / sent date'],missingClose:['مقفلة بلا تاريخ إقفال','Closed without a closure date'],stale:['تغيّرت بعد الاعتماد','Changed after acceptance'],qualityNote:['اكتمال البيانات ليس درجة أداء. لا تُستنتج تواريخ أو ساعات من آخر تعديل للسجل.','Data completeness is not a performance score. Dates and hours are not inferred from the last edit.'],
 capacity:['الطلب والطاقة حسب التخصص','Demand and capacity by skill'],demand:['ساعات الطلب','Demand hours'],supply:['الساعات المتاحة','Available hours'],staffNote:['عرض تقديري من الخطة المدخلة؛ ليس اعتماداً لوظائف. غياب الطاقة يعني «غير مسجلة»، وليس صفراً. لا يتبع فلتر المجال.','An estimate from entered plans, not a staffing approval. Missing capacity is unknown, not zero. Not restricted by the domain filter.'],
 mechanic:['ميكانيكي ديزل','Diesel mechanic'],pump_technician:['فني مضخات','Pump technician'],electrician:['كهربائي','Electrician'],operator:['مشغّل','Operator'],driver:['سائق','Driver'],engineering:['هندسة','Engineering'],support:['دعم الورشة','Workshop support'],unassigned:['غير محدد','Unassigned'],
 noData:['لا توجد بيانات مسجلة لهذا المؤشر في الفترة المختارة.','No recorded data for this indicator in the selected period.'],unknownValue:['غير مسجل','Not recorded'],
 show:['عرض للشاشة الكبيرة','Presentation mode'],play:['تشغيل تلقائي','Auto-play'],pause:['إيقاف مؤقت','Pause'],next:['التالي','Next'],previous:['السابق','Previous'],exit:['إغلاق العرض','Close presentation'],full:['ملء الشاشة','Full screen'],motionOn:['إيقاف الحركة','Motion off'],motionOff:['تشغيل الحركة','Motion on'],reduced:['الحركة مخفّضة بإعداد الجهاز','Motion reduced by device preference'],seconds:['ثوانٍ','seconds'],
 asOf:['تاريخ لقطة المصدر','Source snapshot date'],loaded:['آخر تحميل للبيانات','Last data load'],private:['عرض مقيّد بالصلاحية','Authorized view'],aggregates:['عرض إجمالي بلا أسماء أو ملاحظات خاصة','Aggregate presentation without names or private notes'],refresh:['تحديث البيانات','Refresh data'],resources:['الموارد','Resources'],readiness:['جاهزية المضخات','Pump readiness'],month:['الشهر','Month'],all:['جميع المجالات','All domains'],table:['إظهار بيانات الرسم','Show chart data']
};
let state=null,display=null,slide=0,playing=false,timer=null,requested=true,loadedAt='',lastData=null;
const reduce=root.matchMedia?root.matchMedia('(prefers-reduced-motion: reduce)'):{matches:false};
try{requested=localStorage.getItem('workshop-motion')!=='off';}catch(_){}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tx=(k,lang='ar')=>(D[k]||[k,k])[lang==='en'?1:0];
const num=(v,lang='ar')=>v===null||v===undefined||v===''?'—':new Intl.NumberFormat(lang==='en'?'en':'ar-AE',{maximumFractionDigits:1}).format(v);
const permitted=s=>!!(s?.data?.manager&&s.data.privacyFinalized);
const on=()=>requested&&!reduce.matches&&!document.hidden;
const domainKey=v=>v==='maintenance'?'maintenanceDomain':v||'unknown';
function metrics(data,month,domain='all'){
 const C=root.WorkloadCore,records=data.records.filter(r=>domain==='all'||r.meta.domain===domain),s=C.summary(data,month,domain);
 const cancelled=records.filter(r=>r.cancelled).length,closed=records.filter(r=>!r.cancelled&&r.closed).length;
 const groups=new Map(),types=new Map();
 records.forEach(r=>groups.set(r.meta.domain||'unknown',(groups.get(r.meta.domain||'unknown')||0)+1));
 records.filter(r=>r.kind==='job'&&r.accepted&&C.month(r.meta.acceptedDate,month)).forEach(r=>types.set(r.meta.workType||'unknown',(types.get(r.meta.workType||'unknown')||0)+1));
 const monthParts=/^(\d{4})-(\d{2})$/.exec(month||'');const end=monthParts?new Date(Date.UTC(+monthParts[1],+monthParts[2]-1,1)):new Date();
 const trend=Array.from({length:6},(_,i)=>{const m=new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth()-5+i,1)).toISOString().slice(0,7);const v=C.summary(data,m,domain);return{month:m,tasks:v.tasksReceived,accepted:v.accepted};});
 const closureTasks=records.filter(r=>r.kind==='task'&&!r.cancelled&&r.closed&&C.month(r.meta.closedDate,month));
 const cycles=closureTasks.map(r=>C.days(r.meta.receivedDate,r.meta.closedDate)).filter(Number.isFinite);
 const first=records.filter(r=>r.kind==='task'&&!r.cancelled&&C.month(r.meta.receivedDate,month)).map(r=>C.days(r.meta.receivedDate,r.meta.firstActionDate)).filter(Number.isFinite);
 const waits=closureTasks.filter(r=>(r.waits||[]).some(w=>C.days(w.start,w.end||r.meta.closedDate)!==null)).map(r=>C.waitDays(r.waits,r.meta.receivedDate,r.meta.closedDate)).filter(Number.isFinite);
 return{...s,total:records.length,kindCounts:['task','job','letter'].map(k=>[k,records.filter(r=>r.kind===k).length]),states:[['open',s.open],['closed',closed],['cancelled',cancelled]],groups:[...groups].sort((a,b)=>b[1]-a[1]),types:[...types].sort((a,b)=>b[1]-a[1]),trend,dated:records.filter(r=>C.date(r.meta.receivedDate)!==null).length,classified:records.filter(r=>!!r.meta.domain).length,durations:[['medianCycle',C.median(cycles),cycles.length],['firstAction',C.median(first),first.length],['waiting',C.median(waits),waits.length]],plans:C.staffing(data,month)};
}
function kpi(label,value,l,note='',tone=''){return`<article class="wd-kpi ${tone}"><span>${esc(tx(label,l))}</span><strong data-wd-count="${value==null?'':Number(value)}">${num(value,l)}</strong>${note?`<small>${esc(note)}</small>`:''}</article>`;}
function panel(title,body,l,note=''){return`<section class="wd-panel"><div class="wd-panel-title"><span class="wd-mark" aria-hidden="true"></span><h2>${esc(tx(title,l))}</h2></div>${body}${note?`<p class="wd-note">${esc(tx(note,l))}</p>`:''}</section>`;}
function bars(rows,l,keyMap=x=>x){const max=Math.max(1,...rows.map(r=>r[1]));return rows.length?`<div class="wd-bars">${rows.map(([k,v],i)=>`<div class="wd-bar"><div><span>${esc(tx(keyMap(k),l))}</span><b>${num(v,l)}</b></div><div class="wd-track"><i class="wd-fill tone-${i%4}" style="--wd-fill:${100*v/max}%"></i></div></div>`).join('')}</div>`:`<p class="wd-empty">${esc(tx('noData',l))}</p>`;}
function hero(m,l){return`<section class="wd-hero"><div><p class="wd-eyebrow">${esc(tx('caption',l))}</p><h2>${esc(tx('headline',l))}</h2><p>${esc(tx('intro',l))}</p><div class="wd-splits">${m.kindCounts.map(([k,v])=>`<span><b>${num(v,l)}</b>${esc(tx(k,l))}</span>`).join('')}</div></div><div class="wd-hero-number"><span>${esc(tx('total',l))}</span><strong data-wd-count="${m.total}">${num(m.total,l)}</strong><small>${esc(tx('snapshot',l))}</small></div></section><p class="wd-note">${esc(tx('currentNote',l))}</p><div class="wd-kpis wd-three">${kpi('open',m.open,l,'','wd-blue')}${kpi('overdue',m.overdue,l,'','wd-amber')}${kpi('closed',m.states[1][1],l)}</div>`;}
function monthly(m,l){return panel('monthly',`<div class="wd-kpis">${[['tasksReceived',m.tasksReceived],['jobsReceived',m.jobsReceived],['lettersIn',m.lettersIn],['lettersOut',m.lettersOut],['completed',m.completed],['accepted',m.accepted],['maintenance',m.maintenance],['hours',m.hours]].map(([k,v])=>kpi(k,v,l,k==='hours'?tx('overtime',l)+': '+num(m.overtime,l):'',k==='accepted'?'wd-accent':'')).join('')}</div>`,l,'receiptNote');}
function states(m,l){const total=m.total,a=total?m.open/total*100:0,b=total?m.states[1][1]/total*100:0;return panel('states',`<div class="wd-ring-layout"><div class="wd-ring" role="img" aria-label="${esc(m.states.map(([k,v])=>tx(k,l)+': '+num(v,l)).join('، '))}" style="background:conic-gradient(#267c99 0 ${a}%,#2a9878 ${a}% ${a+b}%,#b5c1c8 ${a+b}% 100%)"><div><strong>${num(total,l)}</strong><span>${esc(tx('records',l))}</span></div></div><div class="wd-legend">${m.states.map(([k,v],i)=>`<div><i class="wd-dot tone-${i}" aria-hidden="true"></i><span>${esc(tx(k,l))}</span><b>${num(v,l)}</b></div>`).join('')}</div></div>`,l);}
function trend(m,l){const rows=m.trend,max=Math.max(1,...rows.flatMap(r=>[r.tasks,r.accepted])),has=rows.some(r=>r.tasks||r.accepted),xs=i=>45+i*102,ys=v=>175-v/max*140;
 const legend=`<div class="wd-trend-legend"><span><i class="wd-dot tone-0"></i>${esc(tx('tasksReceived',l))}</span><span><i class="wd-dot tone-1"></i>${esc(tx('accepted',l))}</span></div>`;
 const svg=has?`<svg class="wd-chart" viewBox="0 0 610 222" role="img" aria-label="${esc(tx('trend',l))}" dir="ltr">${[0,.5,1].map(v=>`<line class="wd-gridline" x1="40" y1="${ys(v*max)}" x2="565" y2="${ys(v*max)}"/><text x="32" y="${ys(v*max)+4}" text-anchor="end">${num(v*max,l)}</text>`).join('')}${['tasks','accepted'].map((k,j)=>`<polyline class="wd-line tone-${j}" points="${rows.map((r,i)=>xs(i)+','+ys(r[k])).join(' ')}"/>${rows.map((r,i)=>`<circle class="wd-point tone-${j}" cx="${xs(i)}" cy="${ys(r[k])}" r="4"><title>${r.month}: ${num(r[k],l)}</title></circle>`).join('')}`).join('')}${rows.map((r,i)=>`<text x="${xs(i)}" y="204" text-anchor="middle">${r.month.slice(2)}</text>`).join('')}</svg>`:`<div class="wd-chart-empty">${esc(tx('trendEmpty',l))}</div>`;
 return panel('trend',legend+svg+`<details class="wd-data-table"><summary>${esc(tx('table',l))}</summary><div class="table-wrap"><table><thead><tr><th>${esc(tx('month',l))}</th><th>${esc(tx('tasksReceived',l))}</th><th>${esc(tx('accepted',l))}</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.month}</td><td>${num(r.tasks,l)}</td><td>${num(r.accepted,l)}</td></tr>`).join('')}</tbody></table></div></details>`,l,'trendNote');}
function durations(m,l){return panel('durations',`<div class="wd-kpis wd-three">${m.durations.map(([k,v,count])=>kpi(k,v,l,tx('days',l)+' · '+tx('sample',l)+': '+num(count,l))).join('')}</div>`,l,'durationNote');}
function quality(m,l){return panel('quality',`<div class="wd-coverage">${[['coverage',m.classified],['dated',m.dated]].map(([key,v])=>`<div><div class="wd-coverage-title"><span>${esc(tx(key,l))}</span><b>${num(v,l)} / ${num(m.total,l)}</b></div><div class="wd-track"><i class="wd-fill" style="--wd-fill:${m.total?100*v/m.total:0}%"></i></div></div>`).join('')}</div><div class="wd-quality-notes"><span>${esc(tx('missingClose',l))}: <b>${num(m.missingClose,l)}</b></span><span>${esc(tx('unknown',l))}: <b>${num(m.unclassified,l)}</b></span><span>${esc(tx('stale',l))}: <b>${num(m.stale,l)}</b></span></div>`,l,'qualityNote');}
function capacity(m,l){return panel('capacity',m.plans.length?`<div class="wd-capacity">${m.plans.map(p=>`<div><h3>${esc(tx(p.skill,l))}</h3>${bars([['demand',p.demand],...(p.capacity===null?[]:[['supply',p.capacity]])],l)}${p.capacity===null?`<p class="wd-note">${esc(tx('supply',l))}: ${esc(tx('unknownValue',l))}</p>`:''}</div>`).join('')}</div>`:`<p class="wd-empty">${esc(tx('noData',l))}</p>`,l,'staffNote');}
function overview(s){if(!permitted(s))return'';const m=metrics(s.data,s.month,s.domain),l=s.lang;return`<div class="wd-dashboard">${hero(m,l)}${monthly(m,l)}<div class="wd-columns">${states(m,l)}${panel('domains',bars(m.groups,l,domainKey),l)}</div>${trend(m,l)}<div class="wd-columns">${panel('activity',bars(m.types,l),l,'activityNote')}${quality(m,l)}</div>${durations(m,l)}${capacity(m,l)}</div>`;}
function button(action,label,l){return`<button type="button" data-wd="${action}">${esc(tx(label,l))}</button>`;}
function refreshMotion(){document.documentElement.dataset.workloadMotion=on()?'on':'off';const b=document.querySelector('[data-wd=motion]');if(b){b.textContent=tx(reduce.matches?'reduced':on()?'motionOn':'motionOff',state?.lang);b.setAttribute('aria-pressed',String(on()));b.disabled=reduce.matches;}if(!on())document.getAnimations?.().filter(a=>a.effect?.target?.closest('.wd-dashboard,#wd-show')).forEach(a=>{try{a.finish();}catch(_){a.cancel();}});}
function animate(node){if(!node||!on())return;node.querySelectorAll('[data-wd-count]').forEach(el=>{const target=el.getAttribute('data-wd-count');if(target===''||!Number.isFinite(Number(target)))return;const v=Number(target),start=performance.now();const frame=t=>{if(!el.isConnected)return;const p=Math.min(1,(t-start)/750);el.textContent=num(v*(1-Math.pow(1-p,3)),state?.lang);if(p<1&&on())requestAnimationFrame(frame);else el.textContent=num(v,state?.lang);};requestAnimationFrame(frame);});}
function stop(){clearTimeout(timer);timer=null;}
function closeShow(){stop();playing=false;if(display?.open)display.close();if(display)display.replaceChildren();document.body.classList.remove('wd-presenting');if(document.fullscreenElement===display)document.exitFullscreen?.().catch(()=>{});}
function panels(s){const m=metrics(s.data,s.month,s.domain),l=s.lang;return[[tx('snapshot',l),hero(m,l)],[tx('monthly',l),monthly(m,l)],[tx('domains',l),`<div class="wd-columns">${states(m,l)}${panel('domains',bars(m.groups,l,domainKey),l)}</div>`],[tx('trend',l),trend(m,l)],[tx('activity',l),`<div class="wd-columns">${panel('activity',bars(m.types,l),l,'activityNote')}${durations(m,l)}</div>`],[tx('quality',l),`<div class="wd-columns">${quality(m,l)}${capacity(m,l)}</div>`]];}
let duration=12000;
function schedule(){stop();if(playing&&!document.hidden){timer=setTimeout(()=>{slide++;paintShow();},duration);}}
function paintShow(){if(!permitted(state)){closeShow();return;}const list=panels(state),l=state.lang;slide=(slide+list.length)%list.length;display.innerHTML=`<div class="wd-show-head"><div><span>${esc(tx('aggregates',l))}</span><h2>${esc(list[slide][0])}</h2><small>${esc(state.month)} · ${esc(state.domain==='all'?tx('all',l):tx(domainKey(state.domain),l))} · ${esc(tx('asOf',l))}: ${esc(state.data.asOf)}</small></div>${button('exit','exit',l)}</div><div class="wd-show-content wd-dashboard">${list[slide][1]}</div><div class="wd-show-foot"><div class="wd-show-buttons">${button('previous','previous',l)}${button('play',playing?'pause':'play',l)}${button('next','next',l)}${button('fullscreen','full',l)}${button('refresh','refresh',l)}</div><label>${esc(tx('seconds',l))} <select id="wd-duration">${[8000,12000,20000].map(v=>`<option value="${v}" ${duration===v?'selected':''}>${v/1000}</option>`).join('')}</select></label><b>${num(slide+1,l)} / ${num(list.length,l)}</b></div><div class="wd-timer"><i style="animation-duration:${duration}ms;animation-play-state:${playing&&!document.hidden?'running':'paused'}"></i></div>`;document.body.classList.add('wd-presenting');refreshMotion();animate(display);schedule();}
function attach(s){state=s;refreshMotion();if(!permitted(s)){closeShow();lastData=null;loadedAt='';return;}if(lastData!==s.data){lastData=s.data;loadedAt=Date.now();}const bar=document.querySelector('.wrap>.bar .actions');if(bar){const toolbar=document.createElement('div');toolbar.className='wd-tools';toolbar.innerHTML=button('show','show',s.lang)+button('motion',on()?'motionOn':'motionOff',s.lang)+`<span class="wd-load">${esc(tx('loaded',s.lang))} <bdi>${esc(new Date(loadedAt).toLocaleTimeString(s.lang==='en'?'en-GB':'ar-AE',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:'Asia/Dubai'}))}</bdi></span>`;bar.prepend(toolbar);}const header=document.querySelector('header .top .actions');if(header){for(const [file,label]of [['resources.html','resources'],['readiness.html','readiness']]){const a=document.createElement('a');a.className='btn wd-context-link';a.href='./'+file;a.target='_top';a.textContent=tx(label,s.lang);header.prepend(a);}}
 if(!display){display=document.createElement('dialog');display.id='wd-show';display.setAttribute('aria-label','عرض الإنجاز / Achievement presentation');document.body.append(display);display.addEventListener('cancel',e=>{e.preventDefault();closeShow();});display.addEventListener('close',stop);}refreshMotion();animate(document.querySelector('.wd-dashboard'));if(display.open)paintShow();}
if(typeof document!=='undefined'){
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-wd]');if(!b)return;const k=b.dataset.wd;if(k==='exit'){closeShow();return;}if(!permitted(state))return;if(k==='show'){slide=0;playing=!reduce.matches;paintShow();display.showModal();}if(k==='motion'){requested=!requested;try{localStorage.setItem('workshop-motion',requested?'on':'off');}catch(_){}refreshMotion();}if(k==='play'){playing=!playing;paintShow();}if(k==='next'||k==='previous'){slide+=k==='next'?1:-1;paintShow();}if(k==='fullscreen'){try{if(document.fullscreenElement)await document.exitFullscreen();else await display.requestFullscreen?.();}catch(_){} }if(k==='refresh')document.querySelector('.wrap [data-action=refresh]')?.click();});
 document.addEventListener('change',e=>{if(e.target.id==='wd-duration'){duration=Number(e.target.value);paintShow();}});
 document.addEventListener('keydown',e=>{if(!display?.open||['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName))return;if(['ArrowRight','ArrowLeft',' '].includes(e.key)){e.preventDefault();if(e.key===' ')playing=!playing;else slide+=e.key==='ArrowRight'?1:-1;paintShow();}});
 document.addEventListener('visibilitychange',()=>{refreshMotion();if(document.hidden)stop();else schedule();});
 root.addEventListener('pagehide',()=>{closeShow();state=null;lastData=null;loadedAt='';});
 reduce.addEventListener?.('change',()=>{if(reduce.matches){playing=false;stop();}refreshMotion();if(display?.open)paintShow();});
 root.addEventListener('beforeprint',()=>document.querySelectorAll('[data-wd-count]').forEach(el=>{const v=el.getAttribute('data-wd-count');if(v!=='')el.textContent=num(Number(v),state?.lang);}));
}
root.WorkloadDashboard={overview,attach,metrics};
})(typeof window!=='undefined'?window:globalThis);
